@startuml

package ZooManagementSystem {

class AquariumFish {
    - age: int
    - length: double
    - colours: Colour[]
    - pattern: Pattern
    - happiness: int
    - LifeSpan: int <<static>>
    - Fish_Noise: String <<final>>
    
    + AquariumFish()
    + AquariumFish(age: int, length: double)
    + static ZooDetails()
    + HowMuchMealFish(): double
    + feed(): double
    + static randomNumberArray(): int[]
    + static randomColour(): Colour[]
    + static randomPattern(): Pattern
    + getLength(): double
    + setLength(length: double)
    + getAge(): int
    + getPattern(): Pattern
    + setAge(age: int)
    + setPattern(pattern: Pattern)
    + getColours(): String
    + static removeDuplicateWords(inputString: String): String
    + setColours(colours: Colour[])
    + makeNoise(): String
    + toString(): String
    + getHappiness(): int
    + setHappiness(happiness: int)
    + ageOneYear(): boolean
}


class CarnivorousAnimal {
    - name: String
    - age: int
    - weight: double
    - gender: Gender
    - happiness: int
    - LifeSpan: int <<static>>
    
    + CarnivorousAnimal()
    + CarnivorousAnimal(name: String, age: int, weight: double, gender: Gender)
    + getHappiness(): int
    + setHappiness(happiness: int)
    + getName(): String
    + setName(name: String)
    + getAge(): int
    + setAge(age: int)
    + getWeight(): double
    + setWeight(weight: double)
    + getGender(): Gender
    + setGender(gender: Gender)
    + ageOneYear(): boolean
}

class ClownFish extends AquariumFish {
    - pattern: Pattern = Pattern.STRIPES
    - colour: Colour[] = {Colour.ORANGE, Colour.BLACK, Colour.WHITE}
    - LifeSpan: int <<static>>
    
    + ClownFish(age: int, length: double)
    + feed(): double
    + toString(): String
    + getColours(): String
    + getPattern(): Pattern
    + ageOneYear(): boolean
}

enum Colour {
    BLACK
    GOLD
    ORANGE
    YELLOW
    WHITE
    GREEN
    BLUE
    BROWN
    RED
    CYAN
}

class Dog {
    - name: String
    - age: int
    - weight: double
    - MeatCalcMale: double <<final>>
    - MeatCalcFemale: double <<final>>
    - Type: DogType
    - gender: Gender
    - happiness: int
    - LifeSpan: int <<static>>
    - DogNoise: String <<final>>
    
    + Dog(name: String, age: int, weight: double, Type: DogType, gender: Gender)
    + getHappiness(): int
    + setHappiness(happiness: int)
    + HowMuchDogEat(): int
    + getName(): String
    + setName(name: String)
    + getAge(): int
    + setAge(age: int)
    + getType(): DogType
    + setType(type: DogType)
    + makeNoise(): String
    + getWeight(): double
    + setWeight(weight: int)
    + ageOneYear(): boolean
    + getGender(): Gender
    + setGender(gender: Gender)
}

enum DogType{
    Akita
    Bulldog
    Poodle
    Terriers
}

enum Gender{
    Male
    Female
}

class GoldFish extends AquariumFish {
    - colour: Colour <<static>>
    - pattern: Pattern = Pattern.CLEAR
    - LifeSpan: int <<static>>
    
    + GoldFish(age: int, length: double)
    + feed(): double
    + static getColour(): Colour
    + static setColour(colour: Colour)
    + getPattern(): Pattern
    + toString(): String
    + getColours(): String
    + ageOneYear(): boolean
}

class HeightException extends Exception {
    + HeightException()
    + HeightException(message: String)
    + HeightIsIllegal(height: double) <<throws HeightException>>
}

class Lion extends CarnivorousAnimal {
  - MeatCalcMale: double = 0.02
  - MeatCalcFemale: double = 0.03
  - MaxMeatinKg: int = 25
  - Lion_Noise: String = "ROAR"

  + Lion()
  + Lion(name: String, age: int, weight: double, gender: Gender)

  + howMuchMeatDoesLionEat(): int
  + feed(): double
  + makeNoise(): String
}

class Lynx extends CarnivorousAnimal {
  - Lynx_Noise: String = "RAAAHHH"
  - MeatCalcMale: double = 1.1
  - MeatCalcFemale: double = 1.3

  + Lynx()
  + Lynx(name: String, age: int, weight: double, gender: Gender)

  + howMuchMeatDoesLynxEat(): int
  + makeNoise(): String
  + feed(): double
}

enum Pattern {
    DOTS
    STRIPES
    SPOTS
    CLEAR
}

class Penguin {
  - height: double
  - age: int
  - name: String
  - LastSortWayused: int = 2
  - LifeSpan: int = 6
  - happiness: int
  - P_noise: String = "squack"

  + Penguin(name: String, age: int, height: double)
  + SortByHeight(arr: List<Penguin>): List<Penguin>
  + SortByAge(arr: List<Penguin>): List<Penguin>
  + SortByName(arr: List<Penguin>): List<Penguin>
  + getLastSortWayused(): int
  + setLastSortWayused(lastSortWayused: int): void
  + Feed_Penguins(fishes: AquariumFish[]): AquariumFish[]
  + feed(): double
  + makeNoise(): String
  + getHeight(): double
  + setHeight(height: double): void
  + getAge(): int
  + setAge(age: int): void
  + getName(): String
  + setName(name: String): void
  + getHappiness(): int
  + setHappiness(happiness: int): void
  + ageOneYear(): boolean
}

class Tiger extends CarnivorousAnimal {
  - Tiger_Noise: String = "roar"
  - MeatCalcMale: double = 0.02
  - MeatCalcFemale: double = 0.03

  + Tiger()
  + Tiger(name: String, age: int, weight: double, gender: Gender)

  + howMuchMeatDoesTigerEat(): int
  + makeNoise(): String
  + feed(): double
}

class Zoo {
  - max_size: int = 1000
  - max_happiness: int = 100
  - name: String
  - location: String
  - penguins: List<Penguin>
  - lions: Lion[]
  - lynxes: Lynx[]
  - dogs: Dog[]
  - fishes: AquariumFish[]
  - tigers: Tiger[]
  - numOfFishColours: int[]
  - numberOfLions: int
  - numberOfPenguins: int
  - numberOfFishes: int
  - numberOfLynxes: int
  - numberOfTigers: int
  - numberOfDogs: int

  + Zoo()
  + getName(): String
  + getLocation(): String
  + getNumberOfLions(): int
  + getNumberOfPenguins(): int
  + getNumberOfTigers(): int
  + getNumberOfLynxes(): int
  + getNumberOfFishes(): int
  + zooDetails(): String
  + printFishes(): String
  + printPenguins(): String
  + printLions(): String
  + printTigers(): String
  + printLynxes(): String
  + printDogs(): String
  + illegalPenguin(height_p: double): boolean
  + addPenguin(newPenguin: Penguin): List<Penguin>
  + AddNewFish(type_f: int, age_f: int, length_f: double, singularFishColours: Colour[], Pattern_F: Pattern)
  + addFish(num: int): AquariumFish[]
  + addLion(newLion: Lion): Lion[]
  + addTiger(newTiger: Tiger): Tiger[]
  + addDog(newDog: Dog): Dog[]
  + addLynx(newLynx: Lynx): Lynx[]
  + Feed_lions(): int
  + Feed_tigers(): int
  + Feed_lynxes(): int
  + FeedDogs(): int
  + Feed_Fishes(): double
  + Feed_penguins(): int
  + Add_New_Penguin(name_p: String, height_p: double, age_p: int): String
  + AddNewLion(name_l: String, weight_l: double, age_l: int, lion_g: int)
  + AddNewTiger(name_t: String, weight_t: double, age_t: int, tiger_g: int)
  + AddNewLynx(name_l: String, weight_l: double, age_l: int, gender_l: int)
  + AddNewDog(name_d: String, age_d: int, weight_d: double, dogtype: int, gender: int)
  + ListentoAllAnimalsinZoo(): String
  + MostPopularFishColour(): String
  + ageOneYearAll(): String
}



}
@enduml